from jaxrl2.agents.resnet_agents.pixel_bc_resnet_learner import PixelResNetBCLearner
from jaxrl2.agents.resnet_agents.pixel_drq_learner import PixelResNetDrQLearner
from jaxrl2.agents.resnet_agents.pixel_iql_learner import PixelResNetIQLLearner
